import turtle

def star():
	
	starTurt = turtle.Turtle()
	starTurt.penup()
	starTurt.left(90)
	starTurt.forward(100)
	starTurt.right(180 - 13.107718)
	# now the turtle is in the starting position, the same action can be repeated to draw the star, which is done with this for loop
	for x in range(1,6):
		starTurt.pendown()
		starTurt.forward(77.755373)
		starTurt.left(261.78564 - 180)
		starTurt.forward(77.755373)
		starTurt.right(333.784564 - 180)
#star()

def circle(): #each circle starts with the turtle rotated 72 degrees so that each of the five circles overlaps in the middle and touches the tips of the star
	cir = turtle.Turtle()
	cir.pencolor("red")
	cir.circle(50)
	cir.right(72)
	cir.pencolor("blue")
	cir.circle(50)
	cir.right(72)
	cir.pencolor("green")
	cir.circle(50)
	cir.right(72)
	cir.pencolor("purple")
	cir.circle(50)
	cir.right(72)
	cir.pencolor("orange")
	cir.circle(50)	
#circle()
	
w =800 # declare width of landscape
h =800 # declare height of landscape

def landFunc():#draws a yellow box on the bottom half of the landscape
	land = turtle.Turtle()
	land.fillcolor("yellow")
	land.begin_fill()
	land.pencolor("yellow")
	land.forward(w/2)
	land.right(90)
	land.forward(h/2)
	land.right(90)
	land.forward(w)
	land.right(90)
	land.forward(h/2)
	land.right(90)
	land.forward(w/2)
	land.end_fill()
	
def skyFunc(): #draws a blue box on the top half of the landscape
	sky = turtle.Turtle()
	sky.fillcolor("blue")
	sky.begin_fill()
	sky.pencolor("blue")
	sky.forward(w/2)
	sky.left(90)
	sky.forward(h/2)
	sky.left(90)
	sky.forward(w)
	sky.left(90)
	sky.forward(h/2)
	sky.left(90)
	sky.forward(w/2)
	sky.end_fill()

def cactusFunc(): #draws a cactus
	cactus = turtle.Turtle()
	cactus.fillcolor("green")
	cactus.begin_fill()
	cactus.pencolor("green")
	cactus.forward(25)
	cactus.left(90)
	cactus.forward(100)
	cactus.right(90)
	cactus.forward(50)
	cactus.left(90)
	cactus.forward(50)
	cactus.left(90)
	cactus.forward(25)
	cactus.left(90)
	cactus.forward(25)
	cactus.right(90)
	cactus.forward(25)
	cactus.right(90)
	cactus.forward(50)
	cactus.left(90)
	cactus.forward(50)
	cactus.left(90)
	cactus.forward(50)
	cactus.right(90)
	cactus.forward(25)
	cactus.right(90)
	cactus.forward(25)
	cactus.left(90)
	cactus.forward(25)
	cactus.left(90)
	cactus.forward(50)
	cactus.left(90)
	cactus.forward(50)
	cactus.right(90)
	cactus.forward(100)
	cactus.left(90)
	cactus.forward(25)
	cactus.end_fill()
	
def desert():
	landFunc()
	skyFunc()
	cactusFunc()

#desert()
	
			
